version: 0.0
os: linux
files:
  - source: /core/target/NotesApplication.war
    destination: /opt/tomcat/apache-tomcat-9.0.16/webapps
hooks:
  BeforeInstall:
    - location: /infrastructure/aws/codedeploy/start_server.sh
  AfterInstall:
    - location: /infrastructure/aws/codedeploy/stop_server.sh
      timeout: 180
  ApplicationStart:
    - location: /infrastructure/aws/codedeploy/start_server.sh
      timeout: 3600