version: 0
os: linux
files:
  -
    source: ./core/target/NotesApplication.war
    destination: /opt/tomcat/apache-tomcat-9.0.16/webapps
hooks:
  hooks:
  BeforeInstall:
    - location: ./infrastructure/aws/codedeploy/start_server.sh
      timeout: 180
      runas: centos
  AfterInstall:
    - location: ./infrastructure/aws/codedeploy/afterInstall.sh
      timeout: 180
      runas: centos
  ApplicationStart:
    - location: ./infrastructure/aws/codedeploy/start_server.sh
      timeout: 180
      runas: centos
  ApplicationStop:
    - location: ./infrastructure/aws/codedeploy/stop_server.sh
      timeout: 180
      runa: centos   
      
