version: 0
os: linux
files:
  -
    source: ./core/target/NotesApplication.war
    destination: /usr/share/tomcat/webapps
hooks:
  hooks:
  BeforeInstall:
    - location: ./start_server.sh
      timeout: 180
      runas: centos
  AfterInstall:
    - location: ./afterInstall.sh
      timeout: 180
      runas: centos
  ApplicationStart:
    - location: ./start_server.sh
      timeout: 180
      runas: centos
  ApplicationStop:
    - location: ./stop_server.sh
      timeout: 180
      runa: centos   
      
