version: 0
os: linux
files:
  -
    source: ./out/artifacts/NotesApplication/NotesApplication.war
    destination: /opt/tomcat/webapps
hooks:
  ApplicationStart:
    -
    location: ./start_server.sh
    timeout: 180
    runas: centos
  ApplicationStop:
    -
    location: ./stop_server.sh
    timeout: 180
    runa: centos    
