version: 2
jobs:
  build:
    branches:
      only: 
          - Assignment5
          - master
    docker:
      -
        image: circleci/openjdk:8-jdk
    steps:
      - checkout
      -
        run:
          name: 'Install packages'
          command: 'sudo apt-get update && sudo apt-get install wget zip unzip -y'
      - 
        run:
          name: 'Install packages'
          command: 'sudo apt-get update && sudo apt-get install maven && sudo apt-get install wget zip unzip python2.7 python-pip -y'
      -
        run:
          name: 'Install awscli'
          command: 'sudo pip install awscli
'
      -
        run:
          name: 'Build Artifact'
          command: "cd core\npwd\nls -al\nmvn clean package -DskipTests\ncd target/\nls -al\ncd ../\npwd\nls -al\n"
      -
        run:
          name: 'Zip Artifact'
          command: |
            echo \"Hello the current build number is ${CIRCLE_BUILD_NUM}\"
            pwd
            mkdir -p codedeploy_artifact
            cp infrastructure/aws/codedeploy/*.sh .
            zip -r csye6225-web-app-${CIRCLE_BUILD_NUM}.zip out/artifacts/NotesApplication/NotesApplication.war *.sh *.yml\nmv csye6225-web-app-${CIRCLE_BUILD_NUM}.zip codedeploy_artifact/\ncd codedeploy_artifact
            ls -al
            pwd
      -
        run:
          name: 'Upload Artifact to S3'
          command: |
            echo ${S3_BUCKET_NAME}
            aws s3 sync codedeploy_artifact s3://code-deploy.csye6225-spring2019-magdanik.me
      -
        run:
          name: 'Make CodeDeploy API call'
          command: "echo \"Hello CodeDeploy\"\n"

